# Day 4 – Feature Engineering for Forecasting

## Objective

The objective of Day 4 is to create model-ready forecasting features from the daily sales dataset.

This includes lag features, rolling averages, time-based features, and a final dataset that can be used for machine learning forecasting models.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

pd.set_option("display.max_columns", None)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
daily_sales = pd.read_csv("../data/processed/daily_sales.csv")

daily_sales["Order Date"] = pd.to_datetime(daily_sales["Order Date"])

print("Daily sales dataset loaded successfully.")
print(daily_sales.shape)

daily_sales.head()

Daily sales dataset loaded successfully.
(1230, 2)

  Order Date     Sales
0 2015-01-03    16.448
1 2015-01-04   288.060
2 2015-01-05    19.536
3 2015-01-06  4407.100
4 2015-01-07    87.158

In [3]:
feature_df = daily_sales.copy()

feature_df["Year"] = feature_df["Order Date"].dt.year
feature_df["Month"] = feature_df["Order Date"].dt.month
feature_df["Quarter"] = feature_df["Order Date"].dt.quarter
feature_df["Week"] = feature_df["Order Date"].dt.isocalendar().week.astype(int)
feature_df["Day"] = feature_df["Order Date"].dt.day
feature_df["DayOfWeek"] = feature_df["Order Date"].dt.dayofweek
feature_df["DayOfYear"] = feature_df["Order Date"].dt.dayofyear
feature_df["IsWeekend"] = (
    feature_df["DayOfWeek"] >= 5
).astype(int)

feature_df.head()

,Order Date,Sales,Year,Month,Quarter,Week,Day,DayOfWeek,DayOfYear,IsWeekend
0,2015-01-03,16.448,2015,1,1,1,3,5,3,1
1,2015-01-04,288.060,2015,1,1,1,4,6,4,1
2,2015-01-05,19.536,2015,1,1,2,5,0,5,0
3,2015-01-06,4407.100,2015,1,1,2,6,1,6,0
4,2015-01-07,87.158,2015,1,1,2,7,2,7,0

In [4]:
print(feature_df.columns)

feature_df.head()

Index(['Order Date', 'Sales', 'Year', 'Month', 'Quarter', 'Week', 'Day',
       'DayOfWeek', 'DayOfYear', 'IsWeekend'],
      dtype='str')

,Order Date,Sales,Year,Month,Quarter,Week,Day,DayOfWeek,DayOfYear,IsWeekend
0,2015-01-03,16.448,2015,1,1,1,3,5,3,1
1,2015-01-04,288.060,2015,1,1,1,4,6,4,1
2,2015-01-05,19.536,2015,1,1,2,5,0,5,0
3,2015-01-06,4407.100,2015,1,1,2,6,1,6,0
4,2015-01-07,87.158,2015,1,1,2,7,2,7,0

In [5]:
feature_df["Lag_1"] = feature_df["Sales"].shift(1)
feature_df["Lag_7"] = feature_df["Sales"].shift(7)
feature_df["Lag_30"] = feature_df["Sales"].shift(30)

feature_df.head(35)

,Order Date,Sales,Year,Month,Quarter,Week,Day,DayOfWeek,DayOfYear,IsWeekend,Lag_1,Lag_7,Lag_30
0,2015-01-03,16.448,2015,1,1,1,3,5,3,1,NaN,NaN,NaN
1,2015-01-04,288.060,2015,1,1,1,4,6,4,1,16.448,NaN,NaN
2,2015-01-05,19.536,2015,1,1,2,5,0,5,0,288.060,NaN,NaN
3,2015-01-06,4407.100,2015,1,1,2,6,1,6,0,19.536,NaN,NaN
4,2015-01-07,87.158,2015,1,1,2,7,2,7,0,4407.100,NaN,NaN
5,2015-01-09,40.544,2015,1,1,2,9,4,9,0,87.158,NaN,NaN
6,2015-01-10,54.830,2015,1,1,2,10,5,10,1,40.544,NaN,NaN
7,2015-01-11,9.940,2015,1,1,2,11,6,11,1,54.830,16.448,NaN
8,2015-01-13,3553.795,2015,1,1,3,13,1,13,0,9.940,288.060,NaN
9,2015-01-14,61.960,2015,1,1,3,14,2,14,0,3553.795,19.536,NaN
10,2015-01-15,149.950,2015,1,1,3,15,3,15,0,61.960,4407.100,NaN
11,2015-01-16,299.964,2015,1,1,3,16,4,16,0,149.950,87.158,NaN
12,2015-01-18,64.864,2015,1,1,3,18,6,18,1,299.964,40.544,NaN
13,2015-01-19,378.594,2015,1,1,4,19,0,19,0,64.864,54.830,NaN
14,2015-01-20,2673.870,2015,1,1,4,20,1,20,0,378.594,9.940,NaN
15,2015-01-23,40.080,2015,1,1,4,23,4,23,0,2673.870,3553.795,NaN
16,2015-01-26,1097.250,2015,1,1,5,26,0,26,0,40.080,61.960,NaN
17,2015-01-27,426.670,2015,1,1,5,27,1,27,0,1097.250,149.950,NaN
18,2015-01-28,3.928,2015,1,1,5,28,2,28,0,426.670,299.964,NaN
19,2015-01-30,240.500,2015,1,1,5,30,4,30,0,3.928,64.864,NaN
20,2015-01-31,290.666,2015,1,1,5,31,5,31,1,240.500,378.594,NaN
21,2015-02-01,468.900,2015,2,1,5,1,6,32,1,290.666,2673.870,NaN
22,2015-02-02,211.646,2015,2,1,6,2,0,33,0,468.900,40.080,NaN
23,2015-02-03,97.112,2015,2,1,6,3,1,34,0,211.646,1097.250,NaN
24,2015-02-04,134.384,2015,2,1,6,4,2,35,0,97.112,426.670,NaN
25,2015-02-06,330.512,2015,2,1,6,6,4,37,0,134.384,3.928,NaN
26,2015-02-07,180.320,2015,2,1,6,7,5,38,1,330.512,240.500,NaN
27,2015-02-08,14.560,2015,2,1,6,8,6,39,1,180.320,290.666,NaN
28,2015-02-11,2043.400,2015,2,1,7,11,2,42,0,14.560,468.900,NaN
29,2015-02-12,129.568,2015,2,1,7,12,3,43,0,2043.400,211.646,NaN
30,2015-02-14,576.726,2015,2,1,7,14,5,45,1,129.568,97.112,16.448
31,2015-02-15,21.360,2015,2,1,7,15,6,46,1,576.726,134.384,288.060
32,2015-02-16,9.040,2015,2,1,8,16,0,47,0,21.360,330.512,19.536
33,2015-02-17,54.208,2015,2,1,8,17,1,48,0,9.040,180.320,4407.100
34,2015-02-18,37.784,2015,2,1,8,18,2,49,0,54.208,14.560,87.158

In [6]:
print(feature_df[["Lag_1", "Lag_7", "Lag_30"]].isnull().sum())

feature_df.head(35)

Lag_1      1
Lag_7      7
Lag_30    30
dtype: int64

,Order Date,Sales,Year,Month,Quarter,Week,Day,DayOfWeek,DayOfYear,IsWeekend,Lag_1,Lag_7,Lag_30
0,2015-01-03,16.448,2015,1,1,1,3,5,3,1,NaN,NaN,NaN
1,2015-01-04,288.060,2015,1,1,1,4,6,4,1,16.448,NaN,NaN
2,2015-01-05,19.536,2015,1,1,2,5,0,5,0,288.060,NaN,NaN
3,2015-01-06,4407.100,2015,1,1,2,6,1,6,0,19.536,NaN,NaN
4,2015-01-07,87.158,2015,1,1,2,7,2,7,0,4407.100,NaN,NaN
5,2015-01-09,40.544,2015,1,1,2,9,4,9,0,87.158,NaN,NaN
6,2015-01-10,54.830,2015,1,1,2,10,5,10,1,40.544,NaN,NaN
7,2015-01-11,9.940,2015,1,1,2,11,6,11,1,54.830,16.448,NaN
8,2015-01-13,3553.795,2015,1,1,3,13,1,13,0,9.940,288.060,NaN
9,2015-01-14,61.960,2015,1,1,3,14,2,14,0,3553.795,19.536,NaN
10,2015-01-15,149.950,2015,1,1,3,15,3,15,0,61.960,4407.100,NaN
11,2015-01-16,299.964,2015,1,1,3,16,4,16,0,149.950,87.158,NaN
12,2015-01-18,64.864,2015,1,1,3,18,6,18,1,299.964,40.544,NaN
13,2015-01-19,378.594,2015,1,1,4,19,0,19,0,64.864,54.830,NaN
14,2015-01-20,2673.870,2015,1,1,4,20,1,20,0,378.594,9.940,NaN
15,2015-01-23,40.080,2015,1,1,4,23,4,23,0,2673.870,3553.795,NaN
16,2015-01-26,1097.250,2015,1,1,5,26,0,26,0,40.080,61.960,NaN
17,2015-01-27,426.670,2015,1,1,5,27,1,27,0,1097.250,149.950,NaN
18,2015-01-28,3.928,2015,1,1,5,28,2,28,0,426.670,299.964,NaN
19,2015-01-30,240.500,2015,1,1,5,30,4,30,0,3.928,64.864,NaN
20,2015-01-31,290.666,2015,1,1,5,31,5,31,1,240.500,378.594,NaN
21,2015-02-01,468.900,2015,2,1,5,1,6,32,1,290.666,2673.870,NaN
22,2015-02-02,211.646,2015,2,1,6,2,0,33,0,468.900,40.080,NaN
23,2015-02-03,97.112,2015,2,1,6,3,1,34,0,211.646,1097.250,NaN
24,2015-02-04,134.384,2015,2,1,6,4,2,35,0,97.112,426.670,NaN
25,2015-02-06,330.512,2015,2,1,6,6,4,37,0,134.384,3.928,NaN
26,2015-02-07,180.320,2015,2,1,6,7,5,38,1,330.512,240.500,NaN
27,2015-02-08,14.560,2015,2,1,6,8,6,39,1,180.320,290.666,NaN
28,2015-02-11,2043.400,2015,2,1,7,11,2,42,0,14.560,468.900,NaN
29,2015-02-12,129.568,2015,2,1,7,12,3,43,0,2043.400,211.646,NaN
30,2015-02-14,576.726,2015,2,1,7,14,5,45,1,129.568,97.112,16.448
31,2015-02-15,21.360,2015,2,1,7,15,6,46,1,576.726,134.384,288.060
32,2015-02-16,9.040,2015,2,1,8,16,0,47,0,21.360,330.512,19.536
33,2015-02-17,54.208,2015,2,1,8,17,1,48,0,9.040,180.320,4407.100
34,2015-02-18,37.784,2015,2,1,8,18,2,49,0,54.208,14.560,87.158

In [7]:
feature_df["Rolling_Mean_7"] = (
    feature_df["Sales"]
    .rolling(window=7)
    .mean()
)

feature_df["Rolling_Mean_30"] = (
    feature_df["Sales"]
    .rolling(window=30)
    .mean()
)

feature_df.head(35)

,Order Date,Sales,Year,Month,Quarter,Week,Day,DayOfWeek,DayOfYear,IsWeekend,Lag_1,Lag_7,Lag_30,Rolling_Mean_7,Rolling_Mean_30
0,2015-01-03,16.448,2015,1,1,1,3,5,3,1,NaN,NaN,NaN,NaN,NaN
1,2015-01-04,288.060,2015,1,1,1,4,6,4,1,16.448,NaN,NaN,NaN,NaN
2,2015-01-05,19.536,2015,1,1,2,5,0,5,0,288.060,NaN,NaN,NaN,NaN
3,2015-01-06,4407.100,2015,1,1,2,6,1,6,0,19.536,NaN,NaN,NaN,NaN
4,2015-01-07,87.158,2015,1,1,2,7,2,7,0,4407.100,NaN,NaN,NaN,NaN
5,2015-01-09,40.544,2015,1,1,2,9,4,9,0,87.158,NaN,NaN,NaN,NaN
6,2015-01-10,54.830,2015,1,1,2,10,5,10,1,40.544,NaN,NaN,701.953714,NaN
7,2015-01-11,9.940,2015,1,1,2,11,6,11,1,54.830,16.448,NaN,701.024000,NaN
8,2015-01-13,3553.795,2015,1,1,3,13,1,13,0,9.940,288.060,NaN,1167.557571,NaN
9,2015-01-14,61.960,2015,1,1,3,14,2,14,0,3553.795,19.536,NaN,1173.618143,NaN
10,2015-01-15,149.950,2015,1,1,3,15,3,15,0,61.960,4407.100,NaN,565.453857,NaN
11,2015-01-16,299.964,2015,1,1,3,16,4,16,0,149.950,87.158,NaN,595.854714,NaN
12,2015-01-18,64.864,2015,1,1,3,18,6,18,1,299.964,40.544,NaN,599.329000,NaN
13,2015-01-19,378.594,2015,1,1,4,19,0,19,0,64.864,54.830,NaN,645.581000,NaN
14,2015-01-20,2673.870,2015,1,1,4,20,1,20,0,378.594,9.940,NaN,1026.142429,NaN
15,2015-01-23,40.080,2015,1,1,4,23,4,23,0,2673.870,3553.795,NaN,524.183143,NaN
16,2015-01-26,1097.250,2015,1,1,5,26,0,26,0,40.080,61.960,NaN,672.081714,NaN
17,2015-01-27,426.670,2015,1,1,5,27,1,27,0,1097.250,149.950,NaN,711.613143,NaN
18,2015-01-28,3.928,2015,1,1,5,28,2,28,0,426.670,299.964,NaN,669.322286,NaN
19,2015-01-30,240.500,2015,1,1,5,30,4,30,0,3.928,64.864,NaN,694.413143,NaN
20,2015-01-31,290.666,2015,1,1,5,31,5,31,1,240.500,378.594,NaN,681.852000,NaN
21,2015-02-01,468.900,2015,2,1,5,1,6,32,1,290.666,2673.870,NaN,366.856286,NaN
22,2015-02-02,211.646,2015,2,1,6,2,0,33,0,468.900,40.080,NaN,391.365714,NaN
23,2015-02-03,97.112,2015,2,1,6,3,1,34,0,211.646,1097.250,NaN,248.488857,NaN
24,2015-02-04,134.384,2015,2,1,6,4,2,35,0,97.112,426.670,NaN,206.733714,NaN
25,2015-02-06,330.512,2015,2,1,6,6,4,37,0,134.384,3.928,NaN,253.388571,NaN
26,2015-02-07,180.320,2015,2,1,6,7,5,38,1,330.512,240.500,NaN,244.791429,NaN
27,2015-02-08,14.560,2015,2,1,6,8,6,39,1,180.320,290.666,NaN,205.347714,NaN
28,2015-02-11,2043.400,2015,2,1,7,11,2,42,0,14.560,468.900,NaN,430.276286,NaN
29,2015-02-12,129.568,2015,2,1,7,12,3,43,0,2043.400,211.646,NaN,418.550857,593.870300
30,2015-02-14,576.726,2015,2,1,7,14,5,45,1,129.568,97.112,16.448,487.067143,612.546233
31,2015-02-15,21.360,2015,2,1,7,15,6,46,1,576.726,134.384,288.060,470.920857,603.656233
32,2015-02-16,9.040,2015,2,1,8,16,0,47,0,21.360,330.512,19.536,424.996286,603.306367
33,2015-02-17,54.208,2015,2,1,8,17,1,48,0,9.040,180.320,4407.100,406.980286,458.209967
34,2015-02-18,37.784,2015,2,1,8,18,2,49,0,54.208,14.560,87.158,410.298000,456.564167

In [8]:
print(
    feature_df[
        ["Rolling_Mean_7", "Rolling_Mean_30"]
    ].isnull().sum()
)

feature_df.head(35)

Rolling_Mean_7      6
Rolling_Mean_30    29
dtype: int64

,Order Date,Sales,Year,Month,Quarter,Week,Day,DayOfWeek,DayOfYear,IsWeekend,Lag_1,Lag_7,Lag_30,Rolling_Mean_7,Rolling_Mean_30
0,2015-01-03,16.448,2015,1,1,1,3,5,3,1,NaN,NaN,NaN,NaN,NaN
1,2015-01-04,288.060,2015,1,1,1,4,6,4,1,16.448,NaN,NaN,NaN,NaN
2,2015-01-05,19.536,2015,1,1,2,5,0,5,0,288.060,NaN,NaN,NaN,NaN
3,2015-01-06,4407.100,2015,1,1,2,6,1,6,0,19.536,NaN,NaN,NaN,NaN
4,2015-01-07,87.158,2015,1,1,2,7,2,7,0,4407.100,NaN,NaN,NaN,NaN
5,2015-01-09,40.544,2015,1,1,2,9,4,9,0,87.158,NaN,NaN,NaN,NaN
6,2015-01-10,54.830,2015,1,1,2,10,5,10,1,40.544,NaN,NaN,701.953714,NaN
7,2015-01-11,9.940,2015,1,1,2,11,6,11,1,54.830,16.448,NaN,701.024000,NaN
8,2015-01-13,3553.795,2015,1,1,3,13,1,13,0,9.940,288.060,NaN,1167.557571,NaN
9,2015-01-14,61.960,2015,1,1,3,14,2,14,0,3553.795,19.536,NaN,1173.618143,NaN
10,2015-01-15,149.950,2015,1,1,3,15,3,15,0,61.960,4407.100,NaN,565.453857,NaN
11,2015-01-16,299.964,2015,1,1,3,16,4,16,0,149.950,87.158,NaN,595.854714,NaN
12,2015-01-18,64.864,2015,1,1,3,18,6,18,1,299.964,40.544,NaN,599.329000,NaN
13,2015-01-19,378.594,2015,1,1,4,19,0,19,0,64.864,54.830,NaN,645.581000,NaN
14,2015-01-20,2673.870,2015,1,1,4,20,1,20,0,378.594,9.940,NaN,1026.142429,NaN
15,2015-01-23,40.080,2015,1,1,4,23,4,23,0,2673.870,3553.795,NaN,524.183143,NaN
16,2015-01-26,1097.250,2015,1,1,5,26,0,26,0,40.080,61.960,NaN,672.081714,NaN
17,2015-01-27,426.670,2015,1,1,5,27,1,27,0,1097.250,149.950,NaN,711.613143,NaN
18,2015-01-28,3.928,2015,1,1,5,28,2,28,0,426.670,299.964,NaN,669.322286,NaN
19,2015-01-30,240.500,2015,1,1,5,30,4,30,0,3.928,64.864,NaN,694.413143,NaN
20,2015-01-31,290.666,2015,1,1,5,31,5,31,1,240.500,378.594,NaN,681.852000,NaN
21,2015-02-01,468.900,2015,2,1,5,1,6,32,1,290.666,2673.870,NaN,366.856286,NaN
22,2015-02-02,211.646,2015,2,1,6,2,0,33,0,468.900,40.080,NaN,391.365714,NaN
23,2015-02-03,97.112,2015,2,1,6,3,1,34,0,211.646,1097.250,NaN,248.488857,NaN
24,2015-02-04,134.384,2015,2,1,6,4,2,35,0,97.112,426.670,NaN,206.733714,NaN
25,2015-02-06,330.512,2015,2,1,6,6,4,37,0,134.384,3.928,NaN,253.388571,NaN
26,2015-02-07,180.320,2015,2,1,6,7,5,38,1,330.512,240.500,NaN,244.791429,NaN
27,2015-02-08,14.560,2015,2,1,6,8,6,39,1,180.320,290.666,NaN,205.347714,NaN
28,2015-02-11,2043.400,2015,2,1,7,11,2,42,0,14.560,468.900,NaN,430.276286,NaN
29,2015-02-12,129.568,2015,2,1,7,12,3,43,0,2043.400,211.646,NaN,418.550857,593.870300
30,2015-02-14,576.726,2015,2,1,7,14,5,45,1,129.568,97.112,16.448,487.067143,612.546233
31,2015-02-15,21.360,2015,2,1,7,15,6,46,1,576.726,134.384,288.060,470.920857,603.656233
32,2015-02-16,9.040,2015,2,1,8,16,0,47,0,21.360,330.512,19.536,424.996286,603.306367
33,2015-02-17,54.208,2015,2,1,8,17,1,48,0,9.040,180.320,4407.100,406.980286,458.209967
34,2015-02-18,37.784,2015,2,1,8,18,2,49,0,54.208,14.560,87.158,410.298000,456.564167

In [9]:
forecast_df = feature_df.dropna().reset_index(drop=True)

print(forecast_df.shape)

forecast_df.head()

(1200, 15)

,Order Date,Sales,Year,Month,Quarter,Week,Day,DayOfWeek,DayOfYear,IsWeekend,Lag_1,Lag_7,Lag_30,Rolling_Mean_7,Rolling_Mean_30
0,2015-02-14,576.726,2015,2,1,7,14,5,45,1,129.568,97.112,16.448,487.067143,612.546233
1,2015-02-15,21.360,2015,2,1,7,15,6,46,1,576.726,134.384,288.060,470.920857,603.656233
2,2015-02-16,9.040,2015,2,1,8,16,0,47,0,21.360,330.512,19.536,424.996286,603.306367
3,2015-02-17,54.208,2015,2,1,8,17,1,48,0,9.040,180.320,4407.100,406.980286,458.209967
4,2015-02-18,37.784,2015,2,1,8,18,2,49,0,54.208,14.560,87.158,410.298000,456.564167

In [10]:
forecast_df.to_csv(
    "../data/processed/forecast_features.csv",
    index=False
)

print("Forecast feature dataset saved successfully.")

Forecast feature dataset saved successfully.

In [11]:
import os

os.listdir("../data/processed")

['daily_sales.csv',
 'forecast_features.csv',
 'monthly_sales.csv',
 'superstore_sales_processed.csv',
 'vgsales_processed.csv',
 'weekly_sales.csv']

# Day 4 Summary

## Tasks Completed

- Loaded daily sales dataset.
- Created time-based features.
- Created lag features (1, 7, 30 days).
- Created rolling average features (7-day and 30-day).
- Removed missing values.
- Saved final forecasting feature dataset.

## Files Created

data/processed/forecast_features.csv

## Skills Learned

- Time Series Feature Engineering
- Lag Features
- Rolling Window Features
- Data Preparation for Forecasting Models

Day 4 successfully completed.